### ISSUE TITLE
Is there a way to get ripser to use virtual memory?

### ISSUE THREAD

**Issue by galenseilis** [scikit-tda/ripser.py#147]
I am considering using Ripser on a precomputed distance matrix of approximately 54 370 points. The size of this distance matrix is too large to fit into my computer's RAM.

The [documentation](https://ripser.scikit-tda.org/en/latest/reference/stubs/ripser.ripser.html) says I can configure the arguments so that I pass in precomputed distance matrix. I was considering using `np.memmap` to represent the distance matrix so that I satisfy my RAM constraints, but it seems that ripser must be trying to construct a similarly-large matrix using `np.meshgrid`.

```python
Traceback (most recent call last):
  File "/path/to/script.py", line 50, in <module>
    pickle.dump(ripser(X=D, distance_matrix=True), 'test_ripser_dump.pickle')
  File "/home/galen/.local/lib/python3.10/site-packages/ripser/ripser.py", line 319, in ripser
    I, J = np.meshgrid(np.arange(n_points), np.arange(n_points))
  File "<__array_function__ internals>", line 5, in meshgrid
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 4373, in meshgrid
    output = [x.copy() for x in output]
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 4373, in <listcomp>
    output = [x.copy() for x in output]
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 22.0 GiB for an array with shape (54370, 54370) and data type int64
```

Is there a way to get ripser to use virtual memory?

**Comment by galenseilis** [comment]
Looking at the [source](https://github.com/scikit-tda/ripser.py/blob/master/ripser/ripser.py) it doesn't look like using virtual memory is an option at this time.

**Comment by galenseilis** [comment]
I guess I could try mounting a large temporary swap partition.
